project:
  type: website
  output-dir: docs


website:
  title: "DrySpells"
  favicon: "Resources/Images/dryspell.png" 
  sidebar:
    logo: "Resources/Images/dryspell.png"
    style: "docked"
    search: true
    contents:
      - index.qmd  
      - preprocessing.qmd  
      - eda.qmd  
      - ml1.qmd  
      - ml2.qmd  

format:
  html:
    theme:
      - cerulean
    toc: true
    css: Resources/CSS/custom.css
    bibliography: dryspell.bib
    date: last-modified
    date-format: long